version: '3.8'

services:
  front:
    image: ex-frontend
    ports:
      - 127.0.0.1:5000:5000
  redis:
    image: redis
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: my_db
  back:
    image: ex-backend
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=my_db
