version: '3.8'

services:
  front:
    image: ex-frontend
    environment:
      - REACT_APP_BACKEND_URL=http://127.0.0.1:80
  redis:
    image: redis
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: my_db
  back:
    image: ex-backend
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=my_db
      - REQUEST_ORIGIN=http://127.0.0.1:80
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 127.0.0.1:80:80
