version: '3.8'

services:
  front:
    build: ./ml-kurkkumopo-frontend
    ports:
      - 127.0.0.1:3000:3000
  back:
    build: ./ml-kurkkumopo-backend
    volumes:
      - model:/src/model
    ports:
      - 127.0.0.1:5000:5000
  train:
    build: ./ml-kurkkumopo-training
    volumes:
      - imgs:/src/imgs
      - data:/src/data
      - model:/src/model

volumes:
  imgs:
  data:
  model:
